### ISSUE TITLE
Magnesium visual glitches with Enigmatica 6 

### ISSUE THREAD

**Issue by banece** [Someone-Else-Was-Taken/Periodic-Table-Reforged#102]
Getting these visual glitches in Enigmatica 6. I'm using Magnesium 1.5 and Enigmatica is running v0.5.20.

Screenshot link: https://imgur.com/a/FPAaulN

**Comment by Someone-Else-Was-Taken** [comment]
Enigmatica 6 has BetterEnd (Forge) Installed.
Magnesium and BEF are not compatible.
