### ISSUE TITLE
Magnesium Causing server to hang when closing

### ISSUE THREAD

**Issue by JT122406** [Someone-Else-Was-Taken/Periodic-Table-Reforged#107]
When running stop the server will not fully close when Magnesium is install instead it gets stuck (hangs) on saving chunks on whatever the last dimension to be saved is.  This is a major issue as it prevents servers from automatically restarting after a crash or auto restarting as part of a normal process as if the server can't exit most scripts can't run a command to start the server.  The only way to exit this hang is to press ctrl+c twice.

**Comment by ghost** [comment]
Is Magnesium even meant to run serverside? #88

**Comment by JT122406** [comment]
> Is Magnesium even meant to run serverside? #88

What do you mean by Magnesium event?

**Comment by ghost** [comment]
> What do you mean by Magnesium event?

What I meant to say was "Is Magnesium meant to run serverside or only client-side?"

**Comment by JT122406** [comment]
> > What do you mean by Magnesium event?
> 
> What I meant to say was "Is Magnesium meant to run serverside or only client-side?"

See I thought so but they added it to the server version of a modpack

**Comment by JT122406** [comment]
Ill just remove it because on the page it says client side
Disregard this issue
