### ISSUE TITLE
"Error in currently selected datapacks" using gilded armor mod

### ISSUE THREAD

**Issue by SkullDiamond** [Someone-Else-Was-Taken/Periodic-Table-Reforged#122]
using the last version of magnesium and gildedarmor this happens 

![image](https://user-images.githubusercontent.com/79324102/142752092-a605ab99-8d75-4cde-8c96-a69d785ae5a9.png)

**Comment by txnitxnichopper** [comment]
How is this a Magnesium issue?

**Comment by SkullDiamond** [comment]
well whiout magnesium the gilded armor mod works

**Comment by txnitxnichopper** [comment]
You should really do the basic fifteen seconds of checking before making issues on unrelated trackers. CurseForge comments are full of people complaining about that mod. And the bug has been reported https://github.com/MaroonShaded/GildedArmor/issues/14

**Comment by SkullDiamond** [comment]
well sorry ....
