### ISSUE TITLE
[Iris]mod compatibility

### ISSUE THREAD

**Issue by OcrSu** [Someone-Else-Was-Taken/Periodic-Table-Reforged#123]
Mods: Iris and ModernUI(https://www.curseforge.com/minecraft/mc-mods/modern-ui)
Log:
[Render thread/INFO] [ModernUI/Core]: Reloaded text layout engine, resolution level: 4.0
[Render thread/WARN] [pupil/]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: modern_text
[Render thread/WARN] [pupil/]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: modern_text
[Render thread/WARN] [pupil/]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: modern_text
.........

**Comment by Entralia** [comment]
I think Iris is a Fabric mod, while Magneisum (aka Sodium Reforged) is a Forge mod
(Magnesium was made as a Forge-port to Sodium, which is a Fabric mod)

Fabric and Forge are different modloaders,
and mods created for each modloader cannot be used by different modloaders
