### ISSUE TITLE
Sodium/Magnesium [v1.5, Minecraft 1.16.5] - Crash with Create's Ponder system

### ISSUE THREAD

**Issue by Elfinlocks** [Someone-Else-Was-Taken/Periodic-Table-Reforged#149]
When using Create's ponder system, the client crashes due to a rendering issue with Magnesium. To replicate, simply install Magnesium v1.5, along with any version of Create, and use the ponder mechanic by holding down "W" when hovering over an appropriate Create item in inventory or JEI.

**Comment by littlepianist** [comment]
mine won't crash when doing the things you have mentioned, also using v1.5 magnesium and create

**Comment by Elfinlocks** [comment]
Added some logs

https://crashy.net/G0nMWJxX5TgG0yeqcKhf
[crash-2021-12-27_09.11.43-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7780581/crash-2021-12-27_09.11.43-client.txt)

**Comment by Elfinlocks** [comment]
Found that this issue is caused by RoadRunner - reporting to them and closing this
