### ISSUE TITLE
Crash With BetterEnd

### ISSUE THREAD

**Issue by viceversagames** [Someone-Else-Was-Taken/Periodic-Table-Reforged#15]
Seems they removed some Fabric-specific code checking for Sodium in their Forge port. Not sure who's end this is on to fix so just linking it here.

https://github.com/Beethoven92/BetterEndForge/issues/182

**Comment by XionioXMaster** [comment]
> This needs to be fixed on BE's Side. I've ported the code for it, I'll create a PR on their end.
> 
> Feel free to compile BE - Reforked for Now as it includes this fix.

Build your Fix BE - Reforked, I can't do it, please!
