### ISSUE TITLE
nothing renders at all 

### ISSUE THREAD

**Issue by spacemex** [Someone-Else-Was-Taken/Periodic-Table-Reforged#150]
![Screenshot (13)](https://user-images.githubusercontent.com/51067067/147788931-003604ca-a64e-43db-8b6f-e769316831ba.png)
nothing renders at all i've created new worlds tried  disabling all the features that were enabled by default. And refreshing the chunks 
ver 1.16.5
modpack i've added this to Delivery INC. 
forge ver 36.1.0
Lwjgl 3 3.22
mod-list to many to mention here is a link to the mod list [Here](https://www.modpackindex.com/modpack/28369/delivery-inc) full link https://www.modpackindex.com/modpack/28369/delivery-inc

**Comment by Entralia** [comment]
Apologies, but Immersive Portals is Incompatible with Magnesium

I have experienced the same issue before

There is no fixing it, besides using Optifine, or another mod that improves FPS, instead of Sodium
(because of how the rendering works on Sodium)

**Comment by spacemex** [comment]
thank i fixed it by deleting magnesium optifine is crashes the modpack i was trying to find  a mod that works with optifine shader
