### ISSUE TITLE
Minecraft will crash with Magnesium pupil (or Iris)

### ISSUE THREAD

**Issue by ButWhyZac** [Someone-Else-Was-Taken/Periodic-Table-Reforged#185]
When using **Pupil-Magnesium** or **Iris-Magnesium** game will crash when loading into world. 
Even with/without Base **Magnesium** inside the mods folder. 

Mods also contained in Mods folder:
emotecraft-for-MC1.16.5-2.1-SNAPSHOT-build.11-forge
Neat-Mod-1.16.5
jei-1.16.3-7.4.0.40
Hwyla-forge-1.10.11-B78_1.16.2

Crash Report txt:
[crash-2022-02-26_15.32.18-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/8145901/crash-2022-02-26_15.32.18-client.txt)

![image](https://user-images.githubusercontent.com/87681327/155829310-d69e107b-1850-44a9-9104-1cb3042a85d9.png)

**Comment by SpinHarmony** [comment]
You should only be using Pupil-Magnesium with Pupil/Lilac. Use Magnesium-1.5 if you aren’t using Pupil/Lilac.

**Comment by ButWhyZac** [comment]
> You should only be using Pupil-Magnesium with Pupil/Lilac. Use Magnesium-1.5 if you aren’t using Pupil/Lilac.

Is there another mod that's just Pupil and not Pupil-Magnesium?

**Comment by SpinHarmony** [comment]
Yes, of course. Lilac/Pupil is SomeoneElse’s Forge port of Iris, while Pupil-Magnesium (technically called Magnesium 1.6) is just an experimental version of Magnesium designed to work with Lilac. You can download Lilac here: [https://www.curseforge.com/minecraft/mc-mods/iris-reforged](https://www.curseforge.com/minecraft/mc-mods/iris-reforged)

**Comment by ButWhyZac** [comment]
I’ll try it out when I get home

Thank you

**Comment by SpinHarmony** [comment]
You’re welcome. :)

**Comment by ButWhyZac** [comment]
After looking at lilac I remember that I saw this before when trying to get Pupil-Magnesium to work, but unfortunately there's no more files to download and it's only avabliable in a modpack called https://www.curseforge.com/minecraft/modpacks/dragon-castle-chicken-duck so i can't download lilac with Pupil-Magnesium.

Although, thank you for replying and helping me out! : )

**Comment by ButWhyZac** [comment]
Actually, I just saw that you're the person who tells people where to download **lilac (pupil)**! 
![image](https://user-images.githubusercontent.com/87681327/157810132-9656bda3-f36f-42ed-b154-25c70f1058a9.png)

And I just want to know if there's a way to grab only **lilac (pupil)** from a modpack.  So I can get it to work with my mods.

**Comment by ButWhyZac** [comment]
Nvm! I got lilac (pupil) to work with forge and with my mods ! 

Thank you for helping me!

**Comment by SpinHarmony** [comment]
You’re welcome! I’m glad it works for you. :)
