### ISSUE TITLE
The monorepo organization prevents easily merging changes between upstream and these ports

### ISSUE THREAD

**Issue by coderbot16** [Someone-Else-Was-Taken/Periodic-Table-Reforged#21]
Copy-pasing the source code of 5 mods into a single repository instead of maintaining a proper forked repository for each port makes it significantly harder to merge from upstream or contribute changes to upstream. This basically guarantees that these mods will fall out of date with the official Fabric versions since it's not simple to merge fixes back in. In addition, it makes Git think that you actually wrote most of the mod code, where the reality is the base code was written others and modified by you.

**Comment by viceversagames** [comment]
> In addition, it makes Git think that you actually wrote most of the mod code, where the reality is the base code was written others and modified by you

lmao please continue crying about it

**Comment by coderbot16** [comment]
Why was this closed? This is still an issue.
