### ISSUE TITLE
My game is crashing when I load a world.

### ISSUE THREAD

**Issue by FruitW0rld** [Someone-Else-Was-Taken/Periodic-Table-Reforged#213]
Here is the crash report.

[Crash report for Github.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/9501592/Crash.report.for.Github.txt)

can you help me with this?

**Comment by TheDeviate** [comment]
> rubidium-0.2.10.jar

> magnesium-1.5.jar

Rubidium and Magnesium are both Sodium ports. They cannot coexist.

**Comment by FruitW0rld** [comment]
I figured it out, but thank you anyways.

**Comment by TheDeviate** [comment]
> I figured it out, but thank you anyways.

I'd recommend closing this since it's resolved.
