### ISSUE TITLE
Please ensure that you are in compliance with section 5 of the GPLv3/LGPLv3

### ISSUE THREAD

**Issue by coderbot16** [Someone-Else-Was-Taken/Periodic-Table-Reforged#22]
Section 5 from https://www.gnu.org/licenses/gpl-3.0.en.html (emphasis mine):

> 5. Conveying Modified Source Versions.
>
> You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:
>
> * a) The work must carry ***prominent*** notices stating that you modified it, and giving ***a relevant date***.
> * b) The work must carry ***prominent*** notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to ***“keep intact all notices”***.
> * c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
> * d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.

In particular, the license files for the relevant mods appear to have been deleted and replaced with the template licenses from the Forge MDK. In addition, the corresponding CurseForge pages fail to have a "Source" link. Finally, neither the CurseForge or GitHub appear to have the required "prominent" notices of modification.

Thanks for your consideration.

**Comment by IMS212** [comment]
Currently this section of the license is invalidated by the readme and license change within the subfolders, please fix this. (And please rename your ports to something original while you're at it.)
