### ISSUE TITLE
mod compatibility with Lucent?

### ISSUE THREAD

**Issue by k1r0s** [Someone-Else-Was-Taken/Periodic-Table-Reforged#30]
[current release](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged/files/3490531) is NOT compatible with https://www.curseforge.com/minecraft/mc-mods/lucent but [prev release](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged/files/3484517) is lmao

by compatible I mean that the game starts. With the current release the game doesn't even start

**Comment by sarim** [comment]
Is there any LambDynamicLights alternative for forge that works with Magnesium?

**Comment by DEWSTREAMING** [comment]
I believe this one does that trick @sarim  https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged although word on the street is you will also want https://www.curseforge.com/minecraft/mc-mods/magnesium-extras to help fix a performance bug

**Comment by sarim** [comment]
> I believe this one does that trick @sarim https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged although word on the street is you will also want https://www.curseforge.com/minecraft/mc-mods/magnesium-extras to help fix a performance bug

Thanks !!! added both and they are really great.
