### ISSUE TITLE
Weird rendering of  CTM Textures

### ISSUE THREAD

**Issue by Jerome226** [Someone-Else-Was-Taken/Periodic-Table-Reforged#35]
Here an example of CTM textures that doesn't seems to work properly with Magnesium.
Happens with all textures that have connected textures.

![image](https://user-images.githubusercontent.com/55724525/137656063-af5a9250-3108-418f-8025-9813cf47dd21.png)

They connect in some weird circumstances.

**Comment by Jerome226** [comment]
This issue seems to be fixed if the user disable Block Face Culling
![image](https://user-images.githubusercontent.com/55724525/137659065-30f58057-9702-4dfe-aa17-7c3b53c438bc.png)

**Comment by martinsebik** [comment]
Disabling Block Face Culling doesn't seem to fix this. Switching it on/off fixes the already placed blocks to connect the way they are supposed to but so does changing the render distance or anything which reloads the chunks but when you place new ctm blocks then they are bugged again.

**Comment by ShibeTemple** [comment]
This is most likely related to the client simply reloading chunks. Using the F3+A keybind also temporarily resolves CTM issues.
