### ISSUE TITLE
[1.16.5 Ragnamod 6] Crash 

### ISSUE THREAD

**Issue by Tealwen** [Someone-Else-Was-Taken/Periodic-Table-Reforged#36]
hi i have a crash with your mod when i am in my base : 

[https://mclo.gs/5IwDn1s](https://mclo.gs/5IwDn1s)

**Comment by Someone-Else-Was-Taken** [comment]
Ragnamod VI currently has an incompatible build of BetterEnd. I would suggest updating to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked
This may fix your issue.
