### ISSUE TITLE
Could you port LambDynamicLights in the future?

### ISSUE THREAD

**Issue by DarkShadow44** [Someone-Else-Was-Taken/Periodic-Table-Reforged#39]
Since sodium/magnesium are a replacement for optifine, there's no good way on forge to get dynamic lights.
Would a port of that mod be possible?

**Comment by Someone-Else-Was-Taken** [comment]
This would be possible. This is a feature I might implement into Magnesium into the future, not sure though.

**Comment by DarkShadow44** [comment]
FYI, there is https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged now.
