### ISSUE TITLE
Incompatibility with Mekanism

### ISSUE THREAD

**Issue by fabrossmann** [Someone-Else-Was-Taken/Periodic-Table-Reforged#41]
Modpack: ATM 6 1.8.7
Magnesium: 1.1.2
Sulfuric: 1.1
Hydrogen Reforged: 1.1

As soon, as you place/load a mekanism Multiblock Tile Enitity (e.g. Wind Turbine) the client crashes. 

[crash-2021-10-21_11.04.56-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7387622/crash-2021-10-21_11.04.56-client.txt)

**Comment by cpm9** [comment]
Has this been fixed? Because placing Mekanism wind turbines works fine for me with Magnesium
