### ISSUE TITLE
Crash when breaking an invisible block in a (corrupted?) chunk

### ISSUE THREAD

**Issue by maicol07** [Someone-Else-Was-Taken/Periodic-Table-Reforged#46]
Crash window (by Not Enough Crashes):

![](https://user-images.githubusercontent.com/9463142/138611799-5c221598-9a7c-4fba-931c-7aa9ef263af1.png)

Crash report: https://gist.github.com/maicol07/014d93b3232b2e2088d84c773ca3a7f2

Crash logs: [debug.zip](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7406209/debug.zip)

The invisible chunks are the same as described here: [https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/45#issuecomment-950354260](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/45#issuecomment-950354260)

**Comment by Someone-Else-Was-Taken** [comment]
This is an issue with BetterEnd (Forge). I would recommend switching to the "Reforked" version or uninstalling either Magnesium or BE.
