### ISSUE TITLE
Critical rendering issue on some devices

### ISSUE THREAD

**Issue by XionioXMaster** [Someone-Else-Was-Taken/Periodic-Table-Reforged#60]
**Magnesium 1.2.2**

We have a large server with Quark, Minecolies, Eidolon, Ice And Fire mods. And for some players the world is not rendered correctly, they can see blocks and dungeons under them! Sometimes they can't see anything at all. Other players are fine.

Here are the characteristics of a person with a problem, if that I do not have this problem, and it occurs in some people

**Laptop**
CPU    Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
RAM    8,00 ГБ 
System    64-x, cpu x64
Video; Intel UHD Graphics 620

Crash: https://paste.loliidc.cn/?51f3224e82133ad5#5eLmjQdvd2HASrSVQkMMDt9upSBuPF9cmYDhAyLUv7uP
Full log: https://paste.loliidc.cn/?2fbaac37ebe048ad#Bniav2UjXGAqUvgyf5n8VfWAdM9jZMuwituW5y5hpKVB

https://media.discordapp.net/attachments/897871478542975057/904102705671323668/2021-10-30_23.17.03.png?width=1191&height=670

https://media.discordapp.net/attachments/897871478542975057/904102742862213200/2021-10-30_23.17.17.png?width=1191&height=670

https://media.discordapp.net/attachments/897871478542975057/904102764047638568/2021-10-30_23.17.49.png?width=1191&height=670

**Comment by DonorKrovi** [comment]
I have the same problem! I thought it was due to the fact that the mod was not finalized, but apparently this is not the case for everyone

i5-9300H CPU
RAM 8,00 gb
Intel HD Graphics 4000

**Comment by gaesyeah** [comment]
same here:

R5 3500x
RAM 16,00 gb
GTX 1660S

**Comment by Someone-Else-Was-Taken** [comment]
Hey, I've been working on a fix, however, I'm unable to replicate the issue on my end.
I intend to push out a build with my "psuedo fix" and some other features, today or tomorrow. It would help a ton if you let me know here if the issue persists on that build.

**Comment by gaesyeah** [comment]
Hi! Unfortunately the problem is still here.

[crash-2021-11-01_04.01.09-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7451288/crash-2021-11-01_04.01.09-client.txt)
[crash-2021-11-01_03.55.19-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7451289/crash-2021-11-01_03.55.19-client.txt)
[crash-2021-11-01_04.07.37-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7451290/crash-2021-11-01_04.07.37-client.txt)

**Comment by HeavyDeception** [comment]
@XionioXMaster I am still having the rendering problem. How was this "Resolved" and can you provide a fix if it is?

**Comment by Xaviewww** [comment]
Hi, I still have this issue too: my world is completely invisible. But in my case, the world hasn't crashed. First pic is with magnesium, second is without.

Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	8.00 GB (7.78 GB usable)
System type	64-bit operating system, x64-based processor

![2021-11-07_14 35 32](https://user-images.githubusercontent.com/93870388/140663418-d4e6cfc7-24cf-4e9b-9be4-2fef14a7d8e2.png)
![2021-11-07_15 03 09](https://user-images.githubusercontent.com/93870388/140663424-f9a7db3f-d906-41e1-8794-a1ccfcd9afe1.png)
.
