### ISSUE TITLE
ItemRendererMixin Crash with Fairy Lights mod

### ISSUE THREAD

**Issue by viceversagames** [Someone-Else-Was-Taken/Periodic-Table-Reforged#62]
in Create: Above and Beyond pack, added Magnesium and crashed.

[crash-2021-11-01_00.19.18-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7450726/crash-2021-11-01_00.19.18-client.txt)

**Comment by m0rtis0** [comment]
Same here, Can confirm. MWE with only Magnesium (No other Performance Mod) is still crashing when giving the "Hanging Lights" https://pastebin.com/MakDFwsT

**Comment by BlackStone5677** [comment]
ye me too
