### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by DonorKrovi** [Someone-Else-Was-Taken/Periodic-Table-Reforged#66]
RX 570 4gb

![image](https://user-images.githubusercontent.com/60231586/140044270-6198800f-7a81-41de-abec-e3d18c0b5048.png)
![image](https://user-images.githubusercontent.com/60231586/140044955-89e23315-0d8a-4b75-a003-00eb5a3ad7f6.png)

[2021-11-03-1.log.gz](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7466848/2021-11-03-1.log.gz)

[crash-2021-11-03_15.29.33-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7466895/crash-2021-11-03_15.29.33-client.txt)

**Comment by HeavyDeception** [comment]
I have this same problem when using the mod.

**Comment by Someone-Else-Was-Taken** [comment]
You appear to be running Create/Flywheel. Mangesium and Flywheel are not compatible by default, this may be the issue.
Run "/flywheel backend off" and let me know if the issue persists

**Comment by HeavyDeception** [comment]
@Someone-Else-Was-Taken Still happening. https://puu.sh/InlQ8/f4dc7292fc.txt
