### ISSUE TITLE
Incompatibility with AE2 Spatial IO

### ISSUE THREAD

**Issue by fabrossmann** [Someone-Else-Was-Taken/Periodic-Table-Reforged#68]
Magnesium: 1.3
Modpack: ATM6 1.8.9

Using Spatial IO from AE2 crashes the client.
https://paste.myftb.de/sovipikofu

**Comment by CommanderKronos** [comment]
Could you add the specifications of your PC? I'm having the same issues.
I made an instance on MultiMC with Minecraft 1.16.5, AE2, Forge and Magnesium. And crashes whenever the items from Spatial IO are rendered (both in JEI and inventory).
Crash log: https://paste.ee/p/Jk2VH

Specs:
AMD Ryzen5 2600
AMD Radeon RX 5700 XT
32 Gb Corsair Vengeance LPX ram @ 3200 Mhz

**Comment by fabrossmann** [comment]
You can see the specs in the crash report, in the last few lines.

**Comment by fabrossmann** [comment]
This issue is still not fixed with version 1.4.1.1: https://paste.myftb.de/alidajozok
