### ISSUE TITLE
Magnesium/ProjectRed rendering issue

### ISSUE THREAD

**Issue by Starkemis** [Someone-Else-Was-Taken/Periodic-Table-Reforged#73]
![DiscordCanary_2tbGtG7aQw](https://user-images.githubusercontent.com/6629056/140634703-b09a3300-703f-4b34-80ec-0a5a0811daa7.png)

Cheers

**Comment by sarim** [comment]
was this fixed? Project Red - Integration mod's logic gates don't render. That may also be related to CB Multipart as its one of Project Red - Integration's dependency.
