### ISSUE TITLE
World not rendering

### ISSUE THREAD

**Issue by Xaviewww** [Someone-Else-Was-Taken/Periodic-Table-Reforged#74]
The blocks in my world appear invisible and 1 can only see certain entities like torch flames and campfire smoke when using magnesium. My game doesn't seem to crash though. (the second picture is without magnesium)

Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	8.00 GB (7.78 GB usable)
System type	64-bit operating system, x64-based processor

![2021-11-07_14 35 32](https://user-images.githubusercontent.com/93870388/140648441-614ace08-98f6-473d-9b86-529748324d41.png)
![2021-11-07_15 03 09](https://user-images.githubusercontent.com/93870388/140648448-c3bb8b07-9ade-4dcf-a363-459c832ec17f.png)

**Comment by Someone-Else-Was-Taken** [comment]
Could you provide a modlist?

**Comment by Xaviewww** [comment]
YUNG's Extras (Forge)
YUNGNICKYOUNG
YungsExtras-Forge-1.16.4-1.0.jar

YUNG's Bridges (Forge)
YUNGNICKYOUNG
YungsBridges-Forge-1.16.4-1.0.1.jar

YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
BetterStrongholds-1.16.4-1.2.1.jar

YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar

YUNG's Better Dungeons (Forge)
YUNGNICKYOUNG
BetterDungeons-1.16.4-1.2.1.jar

YUNG's Better Caves (Forge)
YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.16.4-Forge-13.jar

Wolves With Armor - Forge
Draylar1
wolveswitharmor-1.1.0-1.16.2.jar

Waystones
BlayTheNinth
Waystones_1.16.5-7.6.4.jar

Villagers Respawn
MacTso
VillagersRespawn-1.16.5-1.36.0.4.jar

Villager Names (Forge)
Serilum
villagernames_1.16.5-3.3.jar

Village Spawn Point (Forge)
Serilum
villagespawnpoint_1.16.5-1.8.jar

Village Employment
EnderPreston
village-employment-1.16.5-1.4.1.jar

Vanillo
djroundtable
vanillo-1.1.jar

Vanilla Block Variants
BarionLP
block_variants-1.16.5-2.3.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.6.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-16.0.13a.jar

Upgrade Aquatic
TeamAbnormals
upgrade_aquatic-1.16.5-3.1.0.jar

Unnamed Animal Mod
Coda1552
unnamedanimalmod-1.0.3.jar

Traveler's Titles (Forge)
YUNGNICKYOUNG
TravelersTitles-1.16.4-1.5.jar

Tough As Nails
TheAdubbz
ToughAsNails-1.16.5-4.1.0.9-universal.jar

The Lost Cities
McJty
lostcities-1.16-4.0.10-beta.jar

The Graveyard (FORGE)
finallion_13
The Graveyard 1.1 (FORGE) for 1.16.4-1.16.5.jar

The Abyss: Chapter II
y4z0n
TheAbyss2 1.9.7 1.16.5.jar

TerraForged
won_ton_
TerraForged-1.16.5-0.2.15.jar

TAN Charcoal Filter
Ratatang
TAN_Charcoal_Filter_1.16.5.jar

Sulfuric
someoneelsewastaken
sulfuric-1.1.jar

Stumble Upon: Campsites
PwrDownYT
StumbleUponCampsites.jar

Structures' Compass
Samarium_150
structurescompass-1.16.5-1.2.0.jar

Structures Plus II
Qra5
StructuresPlusEnd.jar

Straw Golem Reborn - Forge
CommodoreThrawn
strawgolem-1.16-1.9.jar

Stoneholm, Underground Villages (Forge)
TheGrimsey
stoneholm-1.2.2.jar

Spiders Produce Webs (Forge)
Serilum
spidersproducewebs_1.16.5-1.4.jar

Spiders 2.0
TheCyberBrick
spiders-2.0-1.16.4-1.0.4.jar

Spice of Life: Potato Edition
Kevun2
solpotato-1.16.X-1.1.0.jar

Spice of Life: Carrot Edition
lordcazsius
SoL-Carrot-1.16.5-1.10.1.jar

Spartan Weaponry
ObliviousSpartan
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar

Spartan Shields
ObliviousSpartan
SpartanShields-1.16.5-2.1.2.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.16.5-3.8.1.384.jar

Serene Shrubbery
Ryukusu
SereneShrubbery-1.16.5-1.1.0.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.16.5-4.0.1.122-universal.jar

Second Chance (Forge)
InfernalStudios
secondchanceforge-1.2.0.jar

Rotten Piglins Mod
abukkezsaruj
RottenPiglinsBug_Fix.jar

RoadRunner
MaxNeedsSnacks
RoadRunner-mc1.16.5-1.3.0.jar

Restored Earth
itayfeder
restored_earth-1.16.5-1.1.1.jar

Repurposed Structures (Forge)
telepathicgrunt
repurposed_structures_forge-3.4.1+1.16.5.jar

Real Target Dummy
kleiders3010
Real Damage Dummy 1.16.5.jar

Random Village Names (Forge)
Serilum
randomvillagenames_1.16.5-1.3.jar

Random Plant Heights (Forge)
Ephys
random_plant_heights-1.0.2.jar

Puddles
OrderedChaosDev
puddles-3.0.0.jar

Project: Vibrant Journeys
OrderedChaosDev
projectvibrantjourneys-1.16.5-3.2.10.jar

Powerful Totems
matyrobbrt
powerfultotems-1.16.5-1.0.jar

Nether Portal Spread (Forge)
Serilum
netherportalspread_1.16.5-5.4.jar

Nether Agriculture
NetherDon_
NetherAgriculture-1.16.5-1.2.1.jar

Nautilium
figiot0
Nautilium.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.14-mc1.16.2.jar

More Villagers
SameDifferent
morevillagers-FORGE-1.16.5-1.5.5.jar

Mo' Structures (Forge)
ffrannny
mostructures-forge-1.2.0-1.16.5.jar

MC Story Mode Armors [Forge / Fabric]
chronos_sacaria
mcsa-forge-2.3.0-Forge.jar

Map Atlases [Forge]
caltinor
MapAtlases-1.16.5-1.2.jar

Majrusz's Accessories
Majrusz17
majruszsaccessories-1.16.5-0.1.4.jar

Majrusz Library
Majrusz17
majrusz-library-1.16.4-2.0.1.jar

Magnesium
someoneelsewastaken
magnesium-1.3.jar

Macaw's Paintings
sketch_macaw
mcw-paintings-1.0.2-mc1.16.5.jar

Loot Beams
shiroroku
lootbeams-1.16.5-release-nov0221.jar

Life Steal Enchantment
TrueRealCursed_Warrior
Life Steal Enchant 1.2.0 - 1.6.5.jar

Law’s Improved Falling Mod
prelawaverage5
LawsImprovedFalling-1.0.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.130.jar

Jungle Villages
HygerianYT
Jungle Villages 1.16.5 v1.1.jar

ItemZoom
mezz
itemzoom-1.16.4-2.3.0.jar

ItemPhysic Lite
CreativeMD
ItemPhysicLite_v1.4.8_mc1.16.5.jar

Infernal Expansion
InfernalStudios
infernal-expansion-2.3.2.jar

Immersive Portals (for Forge)
qouteall
immersive-portals-0.16-mc1.16.5-forge.jar

iChunUtil
ohaiiChun
iChunUtil-1.16.5-10.4.1.jar

I Like Wood - Biomes O' Plenty Plugin
yamahari_
ilikewoodxbiomesoplenty-1.16.5-6.3.0.0.jar

I Like Wood
yamahari_
ilikewood-1.16.5-6.3.0.0.jar

Hwyla
TehNut
Hwyla-forge-1.10.11-B78_1.16.2.jar

Headshot [Forge]
chronos_sacaria
headshot-1.3.0.jar

Guard Villagers
almightytallestred
guardvillagers-1.16.5.1.2.6.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

ForgeEndertech
EnderLanky
ForgeEndertech-1.16.5-7.2.1.0-build.0180.jar

Flywheel
jozufozu
flywheel-1.16-0.2.4.jar

Flamboyant Recrafted
eltrutlikes
flamboyant-1.16.5-1.5.0.jar

Farsight: Spyglasses
HerrBrandstetter
farsight-1.4.1-1.16.5.jar

Farmer's Tea
burritoeatinghamster
farmerstea-1.16.5-1.3.jar

Farmer's Extra Foods
Ratatang
Farmers_Extra_Foods_1.2.jar

Farmer's Delight Compats
burritoeatinghamster
farmersdelightintegrations-1.16.5-1.2.jar

Farmer's Delight
vectorwing
FarmersDelight-1.16.5-0.5.1.jar

Falling Leaves (Forge)
Cheaterpaul
Fallingleaves-1.16.3-1.1.2.jar

ExpandAbility
florensie
expandability-2.0.1-forge.jar

Exline's Wool to String
exlinegames
wooltostring-1.16.5.jar

Exline's Awnings
exlinegames
exlineawnings-1.16.5-1.1.jar

Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons
Corgi_Taco
enhancedcelestials-2.0.8-1.16.5.jar

End Remastered
jack_bagel
endremastered-forge-R4.1.1.jar

Earth Mobs
bagu_chan500
earthmobsmod-1.16.4-0.4.2.jar

Dynamic Trees +
supermassimo0310
DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar

Dynamic Trees - TerraForged
HarleyOConnor
DynamicTreesTerraForged-1.16.5-1.0.0.jar

Dynamic Trees - Biomes O' Plenty
cadaverous_queen
DynamicTreesBOP-1.16.5-2.0.6.jar

Dynamic Trees
ferreusveritas
DynamicTrees-1.16.5-0.10.0-Beta25.jar

Dynamic Surroundings
OreCruncher
DynamicSurroundings-1.16.5-4.0.5.0.jar

Dynamic Music
LudoCrypt
dynmus-1.3.1.jar

Dynamic Lights
atomicstrykergrumpy
dynamiclights-1.16.5.1.jar

Differentiate
eltrutlikes
differentiate-1.16.5-0.5.3.jar

Deeper in the Caves - Warden Mod
LinFoxGamer
Deeper in The Caves Remake 1.1.jar

Dark Paintings
DarkhaxDev
DarkPaintings-1.16.5-6.0.3.jar

Curious Shulker Boxes (Forge)
TheIllusiveC4
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar

Curious Elytra (Forge)
TheIllusiveC4
curiouselytra-forge-1.16.5-4.0.2.3.jar

Curious Armor Stands
ochotonida
Curious Armor Stands-1.16.5-2.1.2.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.3.jar

Curio of Undying (Forge)
TheIllusiveC4
curioofundying-forge-1.16.5-5.2.0.0.jar

Create
simibubi
create-mc1.16.5_v0.3.2f.jar

Cosmetic Netherite
TheMonch__
Cosmetic Netherite 1.16.5.jar

Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.16.5-v4.jar

Comforts (Forge)
TheIllusiveC4
comforts-forge-1.16.5-4.0.1.3.jar

Colt's Cosmetic Armor Mod
Colt_Senpai
ColtCosmeticArmorMod-1.2.5.jar

Collective (Forge)
Serilum
collective-1.16.5-2.64.jar

Colds: Grappler & Ropes (Forge)
Coldspell_Games
ColdsGrappler(Forge1.16.4)vrs1.0.2.jar

Colds: Enchants 2.0
Coldspell_Games
ColdEnchants2.0(Forge1.16.5)vrs1.0.6.jar

Cold Sweat
iMikul
ColdSweat-r2.0.3.1.jar

Clumps
Jaredlll08
Clumps-6.0.0.27.jar

Cloth Config API (Forge)
shedaniel
cloth-config-4.11.26-forge.jar

Citadel
alex_khaan
citadel-1.8.1-1.16.5.jar

Carry On
Tschipp
carryon-1.16.5-1.15.5.15.jar

Campfire Overhaul
ZanderMeister
campfire_overhaul-1.16.5-1.0.5.1.jar

Camp Chair
dmitrylovin
campchair-forge.1.16-1.0.0.jar

Caelus API (Forge)
TheIllusiveC4
caelus-forge-1.16.5-2.1.3.1.jar

Bookshelf
DarkhaxDev
Bookshelf-Forge-1.16.5-10.3.29.jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar

BetterEnd (Forge)
Beethoven92
betterendforge-1.16.5-1.6.3.jar

Best Friend
GrumpyChunks
bestfriend-1.0.jar

Backpacked
MrCrayfish
backpacked-1.10.1-1.16.3.jar

Back Tools
ohaiiChun
BackTools-1.16.5-10.1.0.jar

Artifacts
ochotonida
Artifacts-1.16.5-2.10.3.jar

Armor Toughness Bar
tfarecnim
toughnessbar-6.1.jar

Areas (Forge)
Serilum
areas_1.16.5-2.8.jar

Architectury API (Forge)
shedaniel
architectury-1.24.35-forge.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.16.5-2.1.21.jar

AppleSkin
squeek502
appleskin-forge-mc1.16.x-2.2.0.jar

Antique Atlas
Hunternif
antiqueatlas-6.0.1-forge-mc1.16.5.jar

Ancient Structures
Julek2006Domino
Ancient Structures.jar

Alex's Mobs
alex_khaan
alexsmobs-1.12.1.jar

Adventures Structures
erixon_07
AdventuresStructures_1.0.jar

Additional Bars [FORGE]
Gamma1772
1.16.5-additionalbars-2.0.3.jar

Additional Bars - Biomes O' Plenty addon
Gamma1772
additionalbarsbop-2.0.3.jar

Additional Banners
DarkhaxDev
AdditionalBanners-1.16.5-6.0.3.jar

Abnormals Core
TeamAbnormals
abnormals_core-1.16.5-3.3.0.jar

♪ Alex's Mobs Battle Music ♪
my_name_is_krossy
Alex's Mobs music mod.jar

"To the Bat Poles!"
EnderLanky
AdPoles-1.16.5-5.0.6.0-build.0177.jar

**Comment by Xaviewww** [comment]
Ok i exported it here's the modpa
[Xaview's-0.1.zip](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7493283/Xaview.s-0.1.zip)
ck

**Comment by Xaviewww** [comment]
Thanks!
