### ISSUE TITLE
About Flywheel incompatibility

### ISSUE THREAD

**Issue by gaesyeah** [Someone-Else-Was-Taken/Periodic-Table-Reforged#82]
After some investigation i discovered something. First of all, just remembering: 
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/48
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/60
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/46
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/45#issuecomment-950354260
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/63

Seems the same issue, but after seeing this: https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/67 i tested and yeah...The real problem is the BetterEnd (forge) MOD, im not seeing any visual "glitch" anymore when i load minecraft with BetterEnd Reforked, or just without BetterEnd (forge).

And as we can see here: https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/53 , the issue with flywheel is different.

And i dont know why but in fact, the issue with BetterEnd (forge) isnt happening in every device.

**Comment by Someone-Else-Was-Taken** [comment]
Hey! Thank you for testing this. BE(Forge) has issues with Biome Colors that are fixed in Reforked.

But again, thank you for testing it, I'll have to add a notice to the CF page.

**Comment by gaesyeah** [comment]
I'm glad to help, thank you for making all those "mod ports", such a fantastic job!
