### ISSUE TITLE
Crashing on Server

### ISSUE THREAD

**Issue by SharkieTV** [Someone-Else-Was-Taken/Periodic-Table-Reforged#83]
ShulkerBulletEntity causing crashes on Servers.
I have it in all my Modpacks and removing the mod server side fixes the issue.

Crash - https://pastebin.com/s2VL48Pw

**Comment by Someone-Else-Was-Taken** [comment]
Magnesium is a Client-Side Mod, it doesn't need to be added to the Server (Doesn't do anything either).

**Comment by SharkieTV** [comment]
oh my bad thanks
