### ISSUE TITLE
Magnesium required on server?

### ISSUE THREAD

**Issue by cpm9** [Someone-Else-Was-Taken/Periodic-Table-Reforged#88]
The mod is set up to be required on the server is this intended? Edit: when the server is a forge server

From client latest.log file:
_[11Nov2021 22:21:38.541] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [magnesium]_

It also makes a red X appear in the clients multiplayer menu screen which is confusing to some users
![image](https://user-images.githubusercontent.com/82549089/141414527-d0ae8845-0a8c-4cc9-adc6-bc17e2dce287.png)

**Comment by Elfinlocks** [comment]
This is not purely a Magnesium issue - the Red X problem is a known Forge bug

**Comment by cpm9** [comment]
> This is not purely a Magnesium issue - the Red X problem is a known Forge bug

It's not a forge bug. Its a setting in the mod code. Either the mod says its required on both or required on just the client.

**Comment by cpm9** [comment]
Pretty sure you just have to change this line in the mods.toml file

_# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"_
