### ISSUE TITLE
Mekanism mekasuit night vision is green

### ISSUE THREAD

**Issue by cpm9** [Someone-Else-Was-Taken/Periodic-Table-Reforged#92]
Toggling on the night vision mode with the Mekanism mekasuit head upgraded with the night vision module makes the world green instead of doing proper night vision. 

Also, when the night vision is on it makes the black glitched AE2 drive blocks appear properly (related to #91)

![2021-11-12_21 34 17](https://user-images.githubusercontent.com/82549089/141607773-cb6fb4cf-523d-4dd6-b812-a6fc1e18bbc2.png)

Mekanism-1.16.5-10.0.24.453
magnesium-1.4.1.1.jar

**Comment by WindFox** [comment]
Had to double check, but I did remember correctly.
The green tint is normal. That's how the night vision works with the Mekasuit helmet.

**Comment by ghost** [comment]
WindFox said it is normal
