### ISSUE TITLE
Magnesium 1.5 crash.

### ISSUE THREAD

**Issue by KKotik** [Someone-Else-Was-Taken/Periodic-Table-Reforged#94]
Just pressed options button.
[crash-2021-11-14_23.13.32-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7534574/crash-2021-11-14_23.13.32-client.txt)

**Comment by Someone-Else-Was-Taken** [comment]
Dont use 1.5 unless running Pupil
