### ISSUE TITLE
Crash with Pupil Beta 

### ISSUE THREAD

**Issue by Imayreportbugs** [Someone-Else-Was-Taken/Periodic-Table-Reforged#96]
When creating a new world and open video settings games crashes
[crash-2021-11-14_22.17.18-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7534704/crash-2021-11-14_22.17.18-client.txt) 
[crash-2021-11-14_22.15.54-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7534710/crash-2021-11-14_22.15.54-client.txt)

**Comment by viceversagames** [comment]
Is the beta jar public yet? Or did you build from source?

**Comment by NovaN4** [comment]
It's public

**Comment by Imayreportbugs** [comment]
looks like we need the actual pupil mod and this is only the sodium part
