### ISSUE TITLE
Z-Fighting with certain textures.

### ISSUE THREAD

**Issue by Reshy** [Someone-Else-Was-Taken/Periodic-Table-Reforged#97]
This is one of the more noticeable instances, but it seems to happen only along the horizontal planes of the affected textures.  

![2021-11-14_20 30 01](https://user-images.githubusercontent.com/2096384/141722844-431820fd-a63c-4d61-9fe5-234a06669112.png)

**Comment by Quinteger** [comment]
Try disabling "Use Compact Vertex Format" in video settings.
Its tooltip explicitly states that it can cause z-fightning.
When I disabled it, I got rid of z-fighting on IE workbench and Mekanism gas-burning generator.
